DAMAGE_TYPES = [
    'acid', 
    'bludgeoning',
    'cold', 
    'fire', 
    'force', 
    'lightning', 
    'necrotic', 
    'piercing', 
    'poison', 
    'psychic', 
    'radiant', 
    'slashing', 
    'thunder',
    'bludgeoning, piercing, and slashing from nonmagical attacks',
    'bludgeoning, piercing, and slashing from magical attacks',
]