"""added columns for spells

Revision ID: 0574a2877823
Revises: 3eefab743646
Create Date: 2024-03-06 13:13:14.190718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0574a2877823'
down_revision = '3eefab743646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name=op.f('fk_damage_model_monster_id_monsters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('damage_immunities_table')
    op.drop_table('damage_resistances_table')
    op.drop_table('damage_vulnerabilities_table')
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('at_higher_levels', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('effect_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.drop_column('effect_type')
        batch_op.drop_column('at_higher_levels')

    op.create_table('damage_vulnerabilities_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('damage_type', sa.VARCHAR(), nullable=False),
    sa.Column('monster_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name='fk_damage_vulnerabilities_table_monster_id_monsters_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_resistances_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('damage_type', sa.VARCHAR(), nullable=False),
    sa.Column('monster_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name='fk_damage_resistances_table_monster_id_monsters_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_immunities_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('damage_type', sa.VARCHAR(), nullable=False),
    sa.Column('monster_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name='fk_damage_immunities_table_monster_id_monsters_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('damage_model')
    # ### end Alembic commands ###
