"""added all other tables with full columns

Revision ID: 2c149bee68b8
Revises: 9d11a3029c3a
Create Date: 2024-02-29 17:15:33.263942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c149bee68b8'
down_revision = '9d11a3029c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legendary_action', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lair_action', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_actions_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('condition_immunities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_condition_immunities_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('damage_immunities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_damage_immunities_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('damage_resistances_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_damage_resistances_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('damage_vulnerabilities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_damage_vulnerabilities_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('languages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_languages_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('monster_spells_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spell_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_monster_spells_table_spell_id_spells_table'), 'spells_table', ['spell_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_monster_spells_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('senses_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('distance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passive_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_senses_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('special_abilities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('monster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_special_abilities_table_monster_id_monsters_table'), 'monsters_table', ['monster_id'], ['id'])

    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('casting_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('range_area', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verbal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('somatic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attack_save', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('damage_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.drop_column('damage_type')
        batch_op.drop_column('attack_save')
        batch_op.drop_column('school')
        batch_op.drop_column('material')
        batch_op.drop_column('somatic')
        batch_op.drop_column('verbal')
        batch_op.drop_column('range_area')
        batch_op.drop_column('duration')
        batch_op.drop_column('casting_time')
        batch_op.drop_column('level')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('special_abilities_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_special_abilities_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('senses_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_senses_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('passive_score')
        batch_op.drop_column('distance')
        batch_op.drop_column('name')

    with op.batch_alter_table('monster_spells_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_monster_spells_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_monster_spells_table_spell_id_spells_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('spell_id')

    with op.batch_alter_table('languages_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_languages_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('damage_vulnerabilities_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_damage_vulnerabilities_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('damage_type')

    with op.batch_alter_table('damage_resistances_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_damage_resistances_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('damage_type')

    with op.batch_alter_table('damage_immunities_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_damage_immunities_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('damage_type')

    with op.batch_alter_table('condition_immunities_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_condition_immunities_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('actions_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_actions_table_monster_id_monsters_table'), type_='foreignkey')
        batch_op.drop_column('monster_id')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('lair_action')
        batch_op.drop_column('legendary_action')

    # ### end Alembic commands ###
