"""empty message

Revision ID: 2cc324b0120d
Revises: 9284d8dcd779
Create Date: 2024-03-07 10:47:03.860357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc324b0120d'
down_revision = '9284d8dcd779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_immunities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name=op.f('fk_damage_immunities_table_monster_id_monsters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_resistances_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name=op.f('fk_damage_resistances_table_monster_id_monsters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_vulnerabilities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name=op.f('fk_damage_vulnerabilities_table_monster_id_monsters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('damage_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('damage_type', sa.VARCHAR(), nullable=False),
    sa.Column('monster_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name='fk_damage_model_monster_id_monsters_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('damage_vulnerabilities_table')
    op.drop_table('damage_resistances_table')
    op.drop_table('damage_immunities_table')
    # ### end Alembic commands ###
