"""added source for monsters

Revision ID: 34ce34221146
Revises: 87f1da7c5ec1
Create Date: 2024-03-11 15:47:04.259464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ce34221146'
down_revision = '87f1da7c5ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
