"""moved passive_perception to Monster as column

Revision ID: 515c3d7ff4a7
Revises: 2c149bee68b8
Create Date: 2024-03-01 09:38:51.801286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515c3d7ff4a7'
down_revision = '2c149bee68b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passive_perception', sa.Integer(), nullable=True))

    with op.batch_alter_table('senses_table', schema=None) as batch_op:
        batch_op.drop_column('passive_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senses_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passive_score', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.drop_column('passive_perception')

    # ### end Alembic commands ###
