"""empty message

Revision ID: 5dfc61000015
Revises: 0574a2877823
Create Date: 2024-03-06 14:12:07.737550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfc61000015'
down_revision = '0574a2877823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alignment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.drop_column('alignment')

    # ### end Alembic commands ###
