"""changed saving throw value to int

Revision ID: 73229d57db43
Revises: b5b583ea749d
Create Date: 2024-02-29 15:49:00.622288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73229d57db43'
down_revision = 'b5b583ea749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_throws_table', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_throws_table', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
