"""add bonus action / reaction flags to action

Revision ID: 75a11461774b
Revises: 34ce34221146
Create Date: 2024-04-25 12:34:34.350612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a11461774b'
down_revision = '34ce34221146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_action', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reaction', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions_table', schema=None) as batch_op:
        batch_op.drop_column('reaction')
        batch_op.drop_column('bonus_action')

    # ### end Alembic commands ###
