"""empty message

Revision ID: 7b8a0c295f5f
Revises: cb11e7ddfd4b
Create Date: 2024-02-27 09:20:02.794378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8a0c295f5f'
down_revision = 'cb11e7ddfd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('hit_dice_count', sa.Integer(), nullable=True),
    sa.Column('hit_dice_size', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('challenge_rating', sa.Integer(), nullable=True),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=True),
    sa.Column('spellcasting_level', sa.Integer(), nullable=True),
    sa.Column('spellcasting_ability', sa.String(), nullable=True),
    sa.Column('spell_save_dc', sa.Integer(), nullable=True),
    sa.Column('spell_modifier', sa.Integer(), nullable=True),
    sa.Column('spell_slots_first_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_second_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_third_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_fourth_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_fifth_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_sixth_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_seventh_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_eighth_level', sa.Integer(), nullable=True),
    sa.Column('spell_slots_ninth_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monsters_table')
    # ### end Alembic commands ###
