"""added concentration and source columns

Revision ID: 87f1da7c5ec1
Revises: 105282b322ab
Create Date: 2024-03-11 14:57:53.365570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f1da7c5ec1'
down_revision = '105282b322ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concentration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('concentration')

    # ### end Alembic commands ###
