"""empty message

Revision ID: 9284d8dcd779
Revises: bdf46e33a245
Create Date: 2024-03-07 10:41:25.114845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9284d8dcd779'
down_revision = 'bdf46e33a245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters_table.id'], name=op.f('fk_speed_table_monster_id_monsters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.drop_column('speed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speed', sa.VARCHAR(), nullable=True))

    op.drop_table('speed_table')
    # ### end Alembic commands ###
