"""added sub_category to monster

Revision ID: cb11e7ddfd4b
Revises: 4361faf1672b
Create Date: 2024-02-26 13:58:22.537684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb11e7ddfd4b'
down_revision = '4361faf1672b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters_table', schema=None) as batch_op:
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
