"""empty message

Revision ID: e939e8c6db36
Revises: 2cc324b0120d
Create Date: 2024-03-11 13:58:06.065053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e939e8c6db36'
down_revision = '2cc324b0120d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_effect', sa.String(), nullable=True))
        batch_op.drop_column('effect_type')
        batch_op.drop_column('damage_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spells_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('effect_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('damage_effect')

    # ### end Alembic commands ###
