MONSTER_ONE = {
    "name": "Monday Devil",
    "size": "medium",
    "category": "fiend",
    "armor_class": 10,
    "hit_points": 10,
    "hit_dice_count": 10,
    "hit_dice_size": 10,
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 10,
    "wisdom": 10,
    "charisma": 10,
    "challenge_rating": 10,
    "proficiency_bonus": 2,
    "spellcasting_level": 0,
    "spellcasting_ability": None,
    "spell_save_dc": 0,
    "spell_modifier": 0
}

MONSTER_TWO = {
    "name": "Tuesday Wizard Lizard",
    "size": "medium",
    "category": "humanoid",
    "sub_category": "dragonborn",
    "armor_class": 10,
    "hit_points": 10,
    "hit_dice_count": 10,
    "hit_dice_size": 10,
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 20,
    "wisdom": 10,
    "charisma": 10,
    "challenge_rating": 10,
    "proficiency_bonus": 2,
    "spellcasting_level": 3,
    "spellcasting_ability": "intelligence",
    "spell_save_dc": 12,
    "spell_modifier": 3,
    "spell_slots_first_level": 3,
    "spell_slots_second_level": 2
}

MONSTER_THREE = {
    "name": "Wednesday Worg",
    "size": "large",
    "category": "monstrosity",
    "armor_class": 10,
    "hit_points": 10,
    "hit_dice_count": 10,
    "hit_dice_size": 10,
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 10,
    "wisdom": 10,
    "charisma": 10,
    "challenge_rating": 10,
    "proficiency_bonus": 2
}

MONSTER_FOUR = {
    "name": "Thursday Thayan Zombie Giant",
    "size": "huge",
    "category": "undead",
    "armor_class": 10,
    "hit_points": 10,
    "hit_dice_count": 10,
    "hit_dice_size": 10,
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 10,
    "wisdom": 10,
    "charisma": 10,
    "challenge_rating": 10,
    "proficiency_bonus": 2
}

MONSTER_FIVE = {
    "name": "Friday Flying Monkey",
    "size": "small",
    "category": "fey",
    "armor_class": 10,
    "hit_points": 10,
    "hit_dice_count": 10,
    "hit_dice_size": 10,
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 10,
    "wisdom": 10,
    "charisma": 10,
    "challenge_rating": 10,
    "proficiency_bonus": 2
}